### ISSUE TITLE
请问您可以将imdb.pkl和imageStats.pkl两个文件上传上来吗

### ISSUE THREAD

**Issue by leadalion** [www0wwwjs1/tensorflow-siamese-fc#12]
自己处理数据集的时候速度太慢了，请问可以将这两个文件上传上来吗，谢谢您

**Comment by leadalion** [comment]
还有一个问题，就是找不到object.pkl 请问这个文件是怎样产生的

**Comment by leadalion** [comment]
@www0wwwjs1 请问可以联系您吗，有一些小问题想要问一下

**Comment by ahu-WLL** [comment]
@leadalion ，
你好！你现在有这两个.pkl文件吗？我在处理数据一直处理不好，你可以发给我一下吗？
邮箱：756071775@qq.com
谢谢！！！

**Comment by INTOUCHABLE-VS** [comment]
如果您已经有了这两个文件，可以发给我一份吗?17806260020@163.com
万分感谢！！！
